### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by JCorners68** [beaucarnes/restaurant-reviews#7]
Cannot run server test.  The error snippet is below.  I copied the code and used my own .env file and got the below result.

Any help would be appreciated.

D:\code\Restaurant Reviews\backend>nodemon server
[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server index.js`
D:\code\Restaurant Reviews\backend\index.js:1
import app from "./server.js"
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
[nodemon] app crashed - waiting for file changes before starting...

**Comment by SnakeFighter** [comment]
Try adding:
`"type": "module",`
Inside the top-level braces in package.json.

**Comment by Priyal168** [comment]
I was having the same issue spend hours debugging turns out you don't write 
`import mongodb from './mongodb'; ` like this but `import mongodb from 'mongodb';` but like this as this is a package, same with dotenv.

**Comment by maorazoulay** [comment]
I am getting the same issue, adding "type": "module", does not help
